### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by georgezee** [wodby/adminer#4]
Is it possible to get wodby/adminer compiled for ARM64 support?

From what I see on the Docker hub page, there is some [ARM](https://hub.docker.com/_/adminer?tab=tags) support for Adminer. It's not clear to me if this can be extended easily for ARM64 specifically, as is done with other wodby containers such as [PHP](https://hub.docker.com/r/wodby/php/tags).

**Comment by csandanov** [comment]
linux/arm64 support was added

**Comment by georgezee** [comment]
I went to bed after writing my request and woke up with my containers working! 🎁 

Thanks so much for the quick response!

To help those that might encounter a similar issue, the error I was receiving before this update was:
```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
```
